//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddnRemovePara.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LawDBEntities : DbContext
    {
        public LawDBEntities()
            : base("name=LawDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblPara> tblParas { get; set; }
        public virtual DbSet<tblParaLeft> tblParaLefts { get; set; }
        public virtual DbSet<tblParaRight> tblParaRights { get; set; }
    
        public virtual int sp_ProcInitialize()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ProcInitialize");
        }
    
        public virtual int SP_ProcMove(string choice, string selectedParaID)
        {
            var choiceParameter = choice != null ?
                new ObjectParameter("Choice", choice) :
                new ObjectParameter("Choice", typeof(string));
    
            var selectedParaIDParameter = selectedParaID != null ?
                new ObjectParameter("SelectedParaID", selectedParaID) :
                new ObjectParameter("SelectedParaID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ProcMove", choiceParameter, selectedParaIDParameter);
        }
    }
}
